### ISSUE TITLE
test not running

### ISSUE THREAD

**Issue by GreenRover** [archfz/cypress-terminal-report-demo#4]
It only displays:

npx cypress run

Missing baseUrl in compilerOptions. tsconfig-paths will be skipped
Can't run because no spec files were found.

We searched for specs matching this glob pattern:

**Comment by lgenzelis** [comment]
Hi @GreenRover ! The issue here is that cypress got updated to v10 in this demo repo, but it contains many breaking changes that were not addressed. I'd recommend downgrading cypress to v9 for this demo purpose.

**Comment by archfz** [comment]
Is this still issue with latest version? Will close for now, but please test.
